In [1]:
import numpy as np

# vector

In [2]:
x = np.array([1,2,3])
x

array([1, 2, 3])

### vector addition

In [3]:
y = np.array([3,4,5])
y

array([3, 4, 5])

In [4]:
x + y

array([4, 6, 8])

### scalar product

In [5]:
2 * x

array([2, 4, 6])

### dot/inner product

In [6]:
np.dot(x,y)

26

In [7]:
z = np.array([-1,-1,1])
np.dot(x,z)

0

### projection

In [8]:
np.sqrt( np.dot(y,y) ), np.linalg.norm(y)

(7.0710678118654755, 7.0710678118654755)

In [9]:
y1 = y/np.linalg.norm(y)

In [10]:
np.dot(y1 , x)

3.676955262170047

In [11]:
y1 * np.dot(y1 , x)

array([1.56, 2.08, 2.6 ])

# matrix

In [37]:
A = np.array([1,2,3,4,5,6]).reshape(2,3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### matrix elementwise operations

In [14]:
B = np.array([4,2,3,1,7,2]).reshape(2,3)
B

array([[4, 2, 3],
       [1, 7, 2]])

In [15]:
A + B

array([[ 5,  4,  6],
       [ 5, 12,  8]])

In [16]:
A - B

array([[-3,  0,  0],
       [ 3, -2,  4]])

In [17]:
A * B

array([[ 4,  4,  9],
       [ 4, 35, 12]])

### matrix times matrix

In [18]:
C = B.T
C

array([[4, 1],
       [2, 7],
       [3, 2]])

In [19]:
A.shape, C.shape

((2, 3), (3, 2))

In [20]:
np.dot(A,C)

array([[17, 21],
       [44, 51]])

In [21]:
np.dot(C,A)

array([[ 8, 13, 18],
       [30, 39, 48],
       [11, 16, 21]])

### matrix times vector

In [22]:
np.dot(A,x)

array([14, 32])

### matrix inverse

In [23]:
A = np.array([4,7,2,6]).reshape(2,2)
A

array([[4, 7],
       [2, 6]])

In [24]:
A1 = np.linalg.inv(A)
A1

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [25]:
np.dot(A1,A), np.dot(A,A1)

(array([[1.0000000e+00, 8.8817842e-16],
        [0.0000000e+00, 1.0000000e+00]]),
 array([[1., 0.],
        [0., 1.]]))

# tensor

In [26]:
np.array([1,2,3,4,5,6,7,8]).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# Pandas Dataframe [[tutorial](https://www.youtube.com/watch?v=ZyhVh-qRZPA&list=PL-osiE80TeTsWmV9i9c58mdDCSskIFdDS)]

In [41]:
import pandas as pd
df = pd.DataFrame(C)
df

0  1
0  4  1
1  2  7
2  3  2